export const tutorStats = [
  { label: '认证老师', value: '286' },
  { label: '本周需求', value: '94' },
  { label: '平均响应', value: '18分' },
];

export const tutorFilters = [
  { label: '全部', value: 'all' },
  { label: '找老师', value: 'tutor' },
  { label: '找家长', value: 'req' },
];

export const tutorSubjects = [
  '语文',
  '数学',
  '英语',
  '物理',
  '化学',
  '生物',
  '编程',
  '钢琴',
  '美术',
];

export const tutorRequests = [
  {
    id: 'req-r3',
    type: 'req',
    title: '高三物理冲刺辅导',
    parentName: '孙女士',
    city: '杭州',
    district: '滨江区',
    avatar:
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=240&h=240&q=80',
    grade: '高三',
    subject: '物理',
    subjects: ['物理'],
    distance: 2.3,
    mode: 'both',
    budget: 150,
    frequency: '每周4次',
    createdAt: '3小时前',
    verified: true,
    urgent: true,
    contactName: '孙女士',
    contactPhone: '138****6320',
    fullPhone: '13876546320',
    description:
      '孩子物理基础较弱，希望老师能先补核心概念，再带着做真题。周末和工作日晚间都可以协调，上门优先，也接受线上答疑。',
    expectations: ['有高三冲刺经验', '能做阶段反馈', '沟通耐心'],
  },
  {
    id: 'req-r7',
    type: 'req',
    title: '五年级英语口语陪练',
    parentName: '周先生',
    city: '杭州',
    district: '西湖区',
    avatar:
      'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=240&h=240&q=80',
    grade: '五年级',
    subject: '英语',
    subjects: ['英语'],
    distance: 4.8,
    mode: 'online',
    budget: 90,
    frequency: '每周2次',
    createdAt: '今天',
    verified: false,
    urgent: false,
    contactName: '周先生',
    contactPhone: '136****9271',
    fullPhone: '13648189271',
    description: '孩子英语阅读还不错，口语表达不够自信，希望找老师做轻松的对话练习。',
    expectations: ['口语标准', '课堂活泼', '可线上授课'],
  },
  {
    id: 'req-r9',
    type: 'req',
    title: '初二数学几何专项',
    parentName: '刘女士',
    city: '北京',
    district: '海淀区',
    avatar:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=240&h=240&q=80',
    grade: '初二',
    subject: '数学',
    subjects: ['数学'],
    distance: 1.2,
    mode: 'offline',
    budget: 110,
    frequency: '每周3次',
    createdAt: '1小时前',
    verified: true,
    urgent: false,
    contactName: '刘女士',
    contactPhone: '137****1180',
    fullPhone: '13788011180',
    description: '孩子几何证明题薄弱，希望老师每周固定上门，带错题复盘。',
    expectations: ['初中经验', '错题整理', '可上门'],
  },
  {
    id: 'req-r10',
    type: 'req',
    title: '高一英语阅读提升',
    parentName: '陈先生',
    city: '上海',
    district: '徐汇区',
    avatar:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=240&h=240&q=80',
    grade: '高一',
    subject: '英语',
    subjects: ['英语'],
    distance: 3.6,
    mode: 'both',
    budget: 120,
    frequency: '每周2次',
    createdAt: '2小时前',
    verified: true,
    urgent: false,
    contactName: '陈先生',
    contactPhone: '139****6602',
    fullPhone: '13921106602',
    description: '希望老师帮助孩子梳理阅读方法，兼顾词汇和写作输出。',
    expectations: ['英语专业', '方法清晰', '有反馈'],
  },
  {
    id: 'req-r11',
    type: 'req',
    title: '小学四年级语文作文',
    parentName: '赵女士',
    city: '成都',
    district: '武侯区',
    avatar:
      'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=240&h=240&q=80',
    grade: '四年级',
    subject: '语文',
    subjects: ['语文'],
    distance: 5.1,
    mode: 'offline',
    budget: 80,
    frequency: '每周1次',
    createdAt: '昨天',
    verified: false,
    urgent: false,
    contactName: '赵女士',
    contactPhone: '135****4021',
    fullPhone: '13575194021',
    description: '希望老师培养阅读习惯和作文结构意识，课堂氛围轻松一些。',
    expectations: ['阅读写作', '耐心', '课后练习'],
  },
  {
    id: 'req-r12',
    type: 'req',
    title: '少儿编程入门陪练',
    parentName: '吴先生',
    city: '深圳',
    district: '南山区',
    avatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=240&h=240&q=80',
    grade: '六年级',
    subject: '编程',
    subjects: ['编程'],
    distance: 6.4,
    mode: 'online',
    budget: 130,
    frequency: '每周2次',
    createdAt: '昨天',
    verified: true,
    urgent: false,
    contactName: '吴先生',
    contactPhone: '188****7316',
    fullPhone: '18822037316',
    description: '孩子对 Scratch 和 Python 感兴趣，希望系统入门并完成小项目。',
    expectations: ['项目制', '可线上', '启发式教学'],
  },
];

export const tutorTeachers = [
  {
    id: 'tutor-t2',
    type: 'tutor',
    name: '陈老师',
    title: '985 硕士 · 6年高中数学经验',
    city: '杭州',
    district: '拱墅区',
    avatar:
      'https://images.unsplash.com/photo-1552058544-f2b08422138a?auto=format&fit=crop&w=240&h=240&q=80',
    education: '浙江大学硕士',
    subjects: ['数学', '物理'],
    distance: 1.6,
    mode: 'offline',
    price: 180,
    createdAt: '1小时前活跃',
    verified: true,
    hasFreeTrial: true,
    score: 4.9,
    reviewCount: 128,
    contactName: '陈老师',
    contactPhone: '139****2158',
    fullPhone: '13967012158',
    description:
      '擅长高中数学体系化梳理和压轴题拆解，会根据学生错题建立薄弱点清单，课后提供复盘建议。',
    expectations: ['免费试课30分钟', '可上门', '阶段测评'],
  },
  {
    id: 'tutor-t8',
    type: 'tutor',
    name: '林老师',
    title: '重点小学语文老师 · 阅读写作',
    city: '杭州',
    district: '上城区',
    avatar:
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=240&h=240&q=80',
    education: '汉语言文学本科',
    subjects: ['语文'],
    distance: 3.1,
    mode: 'both',
    price: 120,
    createdAt: '昨天活跃',
    verified: true,
    hasFreeTrial: false,
    score: 4.8,
    reviewCount: 86,
    contactName: '林老师',
    contactPhone: '137****8826',
    fullPhone: '13753318826',
    description: '长期辅导小学阅读理解和作文，课堂节奏温和，重视表达能力和阅读习惯。',
    expectations: ['阅读写作', '可线上', '耐心陪伴'],
  },
  {
    id: 'tutor-t9',
    type: 'tutor',
    name: '李老师',
    title: '清华硕士 · 高中数学竞赛',
    city: '北京',
    district: '海淀区',
    avatar:
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=240&h=240&q=80',
    education: '清华大学硕士',
    subjects: ['数学', '竞赛'],
    distance: 1.2,
    mode: 'both',
    price: 260,
    createdAt: '刚刚活跃',
    verified: true,
    hasFreeTrial: true,
    score: 5.0,
    reviewCount: 210,
    contactName: '李老师',
    contactPhone: '138****5186',
    fullPhone: '13800195186',
    description: '擅长竞赛思维与高考压轴题，能根据学生水平拆分目标。',
    expectations: ['竞赛经验', '可试听', '个性化计划'],
  },
  {
    id: 'tutor-t10',
    type: 'tutor',
    name: '张老师',
    title: '北外本科 · 英语口语与雅思',
    city: '上海',
    district: '徐汇区',
    avatar:
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=240&h=240&q=80',
    education: '北京外国语大学本科',
    subjects: ['英语', '雅思'],
    distance: 3.5,
    mode: 'online',
    price: 160,
    createdAt: '今天活跃',
    verified: true,
    hasFreeTrial: false,
    score: 4.8,
    reviewCount: 95,
    contactName: '张老师',
    contactPhone: '136****0982',
    fullPhone: '13699860982',
    description: '口语纠音、阅读方法和雅思备考均可辅导，课堂节奏轻松高效。',
    expectations: ['口语标准', '可线上', '备考规划'],
  },
  {
    id: 'tutor-t11',
    type: 'tutor',
    name: '王老师',
    title: '浙大博士 · 少儿编程',
    city: '深圳',
    district: '南山区',
    avatar:
      'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?auto=format&fit=crop&w=240&h=240&q=80',
    education: '浙江大学博士',
    subjects: ['编程', '数学'],
    distance: 4.2,
    mode: 'online',
    price: 220,
    createdAt: '2小时前活跃',
    verified: true,
    hasFreeTrial: true,
    score: 4.9,
    reviewCount: 142,
    contactName: '王老师',
    contactPhone: '135****2201',
    fullPhone: '13588212201',
    description: '项目制编程课，擅长用可视化方式解释算法和数学思维。',
    expectations: ['项目作品', '可线上', '启发思维'],
  },
  {
    id: 'tutor-t12',
    type: 'tutor',
    name: '赵老师',
    title: '川大本科 · 初中化学物理',
    city: '成都',
    district: '锦江区',
    avatar:
      'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=240&h=240&q=80',
    education: '四川大学本科',
    subjects: ['物理', '化学'],
    distance: 5.8,
    mode: 'offline',
    price: 110,
    createdAt: '昨天活跃',
    verified: false,
    hasFreeTrial: true,
    score: 4.7,
    reviewCount: 44,
    contactName: '赵老师',
    contactPhone: '189****7006',
    fullPhone: '18982017006',
    description: '初中理科同步辅导，注重实验理解和基础题型梳理。',
    expectations: ['基础提升', '可上门', '耐心'],
  },
];

export const tutorItems = [...tutorRequests, ...tutorTeachers];

export function getTutorItem(id) {
  return tutorItems.find((item) => item.id === id) || tutorRequests[0];
}
